
package opjwsclient.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OPServiceService", targetNamespace = "http://opjws/", wsdlLocation = "http://localhost:8080/OPJWS_war_exploded/services/OPService?wsdl")
public class OPServiceService
    extends Service
{

    private final static URL OPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException OPSERVICESERVICE_EXCEPTION;
    private final static QName OPSERVICESERVICE_QNAME = new QName("http://opjws/", "OPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OPJWS_war_exploded/services/OPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPSERVICESERVICE_WSDL_LOCATION = url;
        OPSERVICESERVICE_EXCEPTION = e;
    }

    public OPServiceService() {
        super(__getWsdlLocation(), OPSERVICESERVICE_QNAME);
    }

    public OPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPSERVICESERVICE_QNAME, features);
    }

    public OPServiceService(URL wsdlLocation) {
        super(wsdlLocation, OPSERVICESERVICE_QNAME);
    }

    public OPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPSERVICESERVICE_QNAME, features);
    }

    public OPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OPService
     */
    @WebEndpoint(name = "OPServicePort")
    public OPService getOPServicePort() {
        return super.getPort(new QName("http://opjws/", "OPServicePort"), OPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OPService
     */
    @WebEndpoint(name = "OPServicePort")
    public OPService getOPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://opjws/", "OPServicePort"), OPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPSERVICESERVICE_EXCEPTION!= null) {
            throw OPSERVICESERVICE_EXCEPTION;
        }
        return OPSERVICESERVICE_WSDL_LOCATION;
    }

}
