
package opjwsclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OPService", targetNamespace = "http://opjws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OPService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerOrders", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetCustomerOrders")
    @ResponseWrapper(localName = "getCustomerOrdersResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetCustomerOrdersResponse")
    @Action(input = "http://opjws/OPService/getCustomerOrdersRequest", output = "http://opjws/OPService/getCustomerOrdersResponse")
    public List<String> getCustomerOrders(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderDetails", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetOrderDetails")
    @ResponseWrapper(localName = "getOrderDetailsResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetOrderDetailsResponse")
    @Action(input = "http://opjws/OPService/getOrderDetailsRequest", output = "http://opjws/OPService/getOrderDetailsResponse")
    public List<String> getOrderDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductDetail", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetProductDetail")
    @ResponseWrapper(localName = "getProductDetailResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetProductDetailResponse")
    @Action(input = "http://opjws/OPService/getProductDetailRequest", output = "http://opjws/OPService/getProductDetailResponse")
    public String getProductDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetCustomerResponse")
    @Action(input = "http://opjws/OPService/getCustomerRequest", output = "http://opjws/OPService/getCustomerResponse")
    public String getCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Purchase")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Purchase", targetNamespace = "http://opjws/", className = "opjwsclient.service.Purchase")
    @ResponseWrapper(localName = "PurchaseResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.PurchaseResponse")
    @Action(input = "http://opjws/OPService/PurchaseRequest", output = "http://opjws/OPService/PurchaseResponse")
    public int purchase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductIds", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetProductIds")
    @ResponseWrapper(localName = "getProductIdsResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.GetProductIdsResponse")
    @Action(input = "http://opjws/OPService/getProductIdsRequest", output = "http://opjws/OPService/getProductIdsResponse")
    public List<String> getProductIds();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://opjws/", className = "opjwsclient.service.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://opjws/", className = "opjwsclient.service.SayHelloWorldFromResponse")
    @Action(input = "http://opjws/OPService/sayHelloWorldFromRequest", output = "http://opjws/OPService/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
